services:
  backend:
    build: ./Backend
    command: ./wait-for-postgres.sh db /Backend
    ports:
      - 5001:5000
    depends_on:
      - db

  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    #volumes:
      #- ./db_postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    

  frontend:
    build: ./Frontend
    ports:
      - "3001:3000"
    
  proxy:
    build: ./Nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
  
  tg-bot:
    build: ./tg_bot
    command: /tg-bot
    ports:
      - 4000:4000
    depends_on:
      - backend

